version: "3"

services:

  runtime-setup:
    image: netty-codec-http3-centos7:centos-7-1.8
    build:
      args:
        java_version : "8.0.412-zulu"

  build:
    image: netty-codec-http3-centos7:centos-7-1.8

  build-leak:
    image: netty-codec-http3-centos7:centos-7-1.8

  deploy:
    image: netty-codec-http3-centos7:centos-7-1.8

  shell:
    image: netty-codec-http3-centos7:centos-7-1.8
